### ISSUE TITLE
Monsters University async

### ISSUE THREAD

**Issue by wowdeathbringer** [domyd/mlp#5]
Hi @domyd,

since you mentioned Monsters University in your readme file, I gave that a try. Demuxed the english TrueHD stream from the english playlist (00800.mpls) and used MKVToolNix 47 to replace the TrueHD stream from the playlist with the demuxed TrueHD stream. When playing the resulting file, the audio becomes noticeably async pretty soon. After about 14 minutes into the movie, the audio was just way ahead of the video, I guess it is like 500ms or so. Tried the file on my laptop and in my home cinema with bitstreaming, both showed the same behaviour.

Since you mentioned Monsters University in your readme, I guess you did do tests with that blu-ray. Could you elaborate, how you're building your finale file and what you're using for playback?

**Comment by domyd** [comment]
I demux the entire disc with MakeMKV (1.15.1) and replace the TrueHD stream with MKVToolNix as well (although back then I used v46, but that shouldn't matter). For playback I use the mpv player on Windows, in my home cinema it's a Plex server coupled with Infuse on Apple TV - a/v sync is on point in both cases.

Is that disc the only one you've got the issue with? Is it still async if you skip ahead in the movie, or does it only drift apart when playing normally? I assume mlp told you at the end that the video/audio length matched?

**Comment by wowdeathbringer** [comment]
I downloaded mpv player, it also happens there. You can skip ahead and it is out of sync. mlp said it was fine at the end of demuxing the TrueHD stream, just -2 audio samples off target. Didn't notice any sync problems on Total Recall, but I didn't continue testing after the problem I encountered with bitstreaming I mentioned in [issue #2](https://github.com/domyd/mlp/issues/2)

**Comment by dastardo** [comment]
@wowdeathbringer you need to demux the video with eac3to, if you use Toolnix you will get sync issues.

**Comment by wowdeathbringer** [comment]
Ok, will have to do some further testing with this. Just demuxed the video stream and the german audio stream (Dolby Digital+) using tsMuxer and muxed everything together with MKVToolNix. At first glance the sync problem with the english TrueHD track seem to be gone, but I'll have to verify if the whole movie works in this version first.

@domyd the output window of tsMuxer displayed that it was removing duplicated samples on the german DD+ stream as well. So it seems that DD+ also has overlapping audio parts, just like TrueHD? Could mlp also support DD+ streams? What about other audio formats (all the DTS formats), can they have overlapping audio too?

@dastardo , do you have any clue as to why there're sync issues when using MKVToolNix?

**Comment by domyd** [comment]
Yeah, it appears that AC3 and DTS also have overlapping frames on blu-rays, but MakeMKV & co. seem to be able to handle them far better than they do TrueHD so I've never investigated those (they're also much older formats). It's on my todo list, but I really hope they're fine for my blu-ray collection's sake 😀

**Comment by dastardo** [comment]
@wowdeathbringer I guess Toolnix just isn't very good at seamless branching.  If you demux first with eac3to you shouldn't have any sync problems, it takes longer but it's the best method.

**Comment by domyd** [comment]
Closing this issue then as it appears to be a muxing problem.
