### ISSUE TITLE
Newbie question: what do I do with the output?

### ISSUE THREAD

**Issue by pcolmer** [domyd/mlp#7]
I've come here because I'm struggling with an issue experienced with a UHD rip from MakeMKV and I'm trying to see if it is the rip that is the problem or the playback tool.

So, given some of the points made about how MakeMKV handles the problem that mlp addresses, I'm wondering if I can (somehow) use MakeMKV and mlp to generate a *better* rip.

Hence my question: if I use mlp to create an output file, presumably that is the TrueHD audio only so what do I do with it next in order to re-mux it with the file created by MakeMKV? Or do I need to run mlp against a backup created by MakeMKV and then do something after that?

Thanks 👍

**Comment by domyd** [comment]
You'd use `mkvtoolnix` (or similar muxing tools). You'll want to give it the `.mkv` generated by MakeMKV as well as the TrueHD stream generated by this tool, and basically swap it out.

![image](https://user-images.githubusercontent.com/5590413/89735119-8584a600-da60-11ea-8bd2-374447e7d176.png)

The highlighted entry is the separate stream. It has ID 0, no language and title, which you'll wanna fill out. Deselect the included stream (with ID 1 or higher), select a destination, and press "Start multiplexing" 🙂

**Comment by pcolmer** [comment]
My apologies for not replying sooner. Just wanted to say thank you for your help. I think I've managed to correctly re-mux the audio track created by `mlp` back into the mkv file created by MakeMKV. I need to do some more playback testing with Kodi but early signs are that it is playing well, so fingers crossed that this has solved my problem.
